### ISSUE TITLE
Paste feature

### ISSUE THREAD

**Issue by azlux** [josephernest/Yopp#11]
Hi,
Do you think a better paste feature can be made for computer ?
Now, people use more the drag-and-drop and copy/paste than select the file on the computer.

I've found [some code](https://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c) but I've haven't implement it.
Az

**Comment by josephernest** [comment]
Hi @azlux 
Good idea! Drag&drop is already implemented, but copy/paste not yet. Feel free to add this feature, and post a pull request (if so please send an URL link of a sandbox version, so that I can test it).
Thank you very much.
