### ISSUE TITLE
Glitch Upload 

### ISSUE THREAD

**Issue by tiaxter** [josephernest/Yopp#4]
When i try to upload something, for example MP3 Files or other I obtain a glitched Upload Text and the file i Selected it isn't uploaded
![image](https://user-images.githubusercontent.com/33230281/32183301-41f026f8-bd99-11e7-88b9-f58b2babe3a6.png)

**Comment by josephernest** [comment]
Hi @tiaxter, I'm unable to reproduce this error. Have you modified the code? What is the server OS (which distrib) + web server (apache?). Is the client Chromium on Linux?

Please share an URL of a temporary instance (you'll change the URL to a private one later), and I'll test on my browser.

**Comment by tiaxter** [comment]
I am using Debian, I installed the last version of Apache and the last version of PHP, using apt-get install 'apache*' php

**Comment by tiaxter** [comment]
I didn't edit the code, and I can't share the url

**Comment by tiaxter** [comment]
Today morning I found this guide , I followed this: https://bash-prompt.net/guides/simple-file-transfer/

**Comment by josephernest** [comment]
Cool tutorial, thanks for the link. 

In fact it's even simpler than this, you don't need any `nohup php -S 172.31.45.14:3748 -t /var/www/yopp > /dev/null 2>&1 &` nor any `php -S <interface>:<port> -t document_root`. If you have a Apache running, just copy the index.php file in a folder, and that's it. No such command-line action is required.

As we can't reproduce this error, this is difficult to solve. Probably related to you local config?
